.eslintrc.json
Have changed the eslintrc.json file to fix the Delete "CR" error.
=> Fixed Delete CR error

.eslintrc.json, package-lock.json, package.json, src/app/layout.tsx
Added the Radix Dapp Toolkit initiation and Radix Connect button to the layout.tsx file. User can now connect and disconnect from a radix testnet wallet and select the account they want to expose.
closes #12
=> Added radix Connect button

src/app/layout.tsx
=> removes exporting metadata from layout.tsx

.github/workflows/lint.yml, .prettierignore, .vscode/extensions.json, README.md, src/app/PriceChart.tsx, src/app/page.tsx
=> Eslint prettier ci check

src/app/NewOrder.tsx, src/app/PairInfo.tsx, src/app/PairsList.tsx, src/app/layout.tsx
Small fixes for ui for it to be usable for manual testing.
=> Order-input-visibility

src/app/OrderBook.tsx, src/app/PairInfo.tsx, src/app/PairsList.tsx, src/app/PriceChart.tsx, src/app/adex-state-context.ts, src/app/contexts.ts, src/app/layout.tsx, src/app/page.tsx
=> Fix  build error

.vscode/extensions.json, __tests__/OrderBook.test.ts, __tests__/utils.test.ts, jest.config.mjs, package-lock.json, package.json, src/app/Footer.tsx, src/app/NavBar.tsx, src/app/OrderBook.tsx, src/app/PairInfo.tsx, src/app/layout.tsx, src/app/orderbook.css, src/app/utils.ts
closes #32 
- consolidates Orderbook-related elements in single .tsx component
- adds spread
- adds total column
=> Order book

package-lock.json, package.json, src/app/components/OrderBook.tsx, src/app/components/OrderInput.tsx, src/app/redux/orderInputSlice.ts, src/app/redux/pairSelectorSlice.ts, src/app/redux/radixSlice.ts, src/app/subscriptions.ts
Also fixes the [price to be token2](https://github.com/DeXter-on-Radix/website/pull/73#discussion_r1300327750), another discussion about it - [on discord](https://discord.com/channels/1125689933735145503/1125689934251032584/1144186042468020244)
=> Update adex to 0.8

src/app/components/OrderInput.tsx, tailwind.config.js, tsconfig.json
now you can use your import paths like this i.e 
import Navbar from "components/NavBar";
you can directly refer everything inside src/app folder now.
=> config: absolute path imports

package-lock.json, package.json, src/app/subscriptions.ts
If someone could review and approve this quickly. I just updated the alphadex sdk to the latest version.
=> Updated alphadex sdk to 0.9.0

src/app/components/OrderBook.tsx, src/app/redux/orderBookSlice.ts
Fix issue #111
Small (one line) fix to correct the spread % calculation in the orderbook component.
=> fix spread percentage

src/app/page.tsx
=> Removing min height to fix footer

src/app/redux/accountHistorySlice.ts
=> fixes undefined error for order history

public/.well-known/radix.json, src/app/subscriptions.ts
=> updates stokenet DeXter address

src/app/layout.tsx, src/app/page.tsx
=> fix balance and history update

package-lock.json, package.json, src/app/components/OrderBook.tsx, src/app/components/order_input/AmountInput.tsx, src/app/components/order_input/LimitOrderInput.tsx, src/app/components/order_input/MarketOrderInput.tsx, src/app/debounce.ts, src/app/redux/orderInputSlice.ts, src/app/redux/pairSelectorSlice.ts, src/app/utils.ts
=> Decimals Mask

package-lock.json, package.json, src/app/state/orderInputSlice.ts
fixes #189
an error message instead of automatic amount substitution
=> fix market order input auto amount update

src/app/components/PairSelector.tsx, src/app/state/orderInputSlice.ts
=> fix pricing carrying over from previous pair

src/app/state/orderBookSlice.ts
=> avoiding zero grouping

src/app/components/PairSelector.tsx
Fixes issue with Longer dropdowns, having interactive elements behind take priority causes some items to be unselectable
=> tweaked z-index

src/app/components/PriceChart.tsx
Reupload of PR #242.
Fixes #240.
Before/After:
=> fix border

package-lock.json, package.json, src/app/components/PriceChart.tsx, src/app/state/priceChartSlice.ts, tailwind.config.js
fixes #225
fixes #233
before:
after:
=> Fix-chart-colors

src/app/components/OrderBook.tsx, src/app/components/order_input/MarketOrderInput.tsx, src/app/state/locales/en/trade.json, src/app/state/locales/pt/trade.json
fix 2 errors:
- add translation for ORDER COUNT
- make slippage limit input max-width 100px
=> I18n static preload

__tests__/orderBookSlice.test.ts, src/app/state/orderBookSlice.ts
fixes #232
- fix unit test TS errors
- add unit tests for grouping calculations
=> fix unit test TS errors

.github/workflows/stokenet-deploy-main.yml
This will probably fix errors like the in the following build - https://github.com/DeXter-on-Radix/website/actions/runs/8506457417/job/23296682999
=> fix "next export" command error

src/app/components/DexterToaster.tsx, src/app/layout.tsx, src/app/state/locales/pt/trade.json
Final changes to toaster notifications as discussed in discrod UI/UX thread:
1. change position to `top-center` for all operating systems
2. change background color to make the notification slightly more noticable
=> Toaster Notifications: place on top-center + adapt BG color + fix translation

src/app/components/Rewards.tsx, src/app/utils.ts
Those features were added:
- when user is logged out, it shows "please login to claim rewards"
- as soon as the user gets logged in, the component fetches the rewards automatically
- during fetching, a loading state is shown "loading fetching rewards".
in summary, theres 3 states now: (1) user logged out (2) user logged in and rewards are fetching (3) user logged in and rewards succesfully fetched. One state that should still be added is the case when fetching rewards fails for some reason.
=> wait for RDK to be ready before fetching rewards

src/app/data/stokenetTokens.json, src/app/layout.tsx, src/app/rewards/page.tsx, src/app/state/locales/en/rewards.json, src/app/state/locales/pt/rewards.json
Added:
- json data prettified
- improve translations
- enabled testing: submit button now actually tries to claim rewards
- fixed footer bug
=> Claims component enable testing

src/app/components/PriceInfo.tsx, src/app/page.tsx
=> fixed wrong currency used in price info

src/app/rewards/page.tsx, src/app/state/rewardSlice.ts, src/app/state/rewardUtils.tsx
Added some final non-breaking changes:
- removed unneeded comments
- added missing error logging
=> Remove unneeded code + add error logging

src/app/components/OrderInput.tsx, src/app/state/orderInputSlice.test.ts
Fixed bugs:
- update balance after order is submitted (reported by [@davimeloag](https://t.me/Davimeloag))
- update balance after data sharing is updated
- when selecting MAX: reserve 3 XRD to pay transaction fees (reported and suggested by [@John101P](https://t.me/John101P))
=> Buy sell panel fix bugs

CONTRIBUTING.md
This is just a dummy PR to merge with main to force a redeploy.
=> silly change to contributing.md

src/app/state/priceChartSlice.ts
=> [BUGFIX] fix first candle not showing legend

src/app/rewards/page.tsx
=> [BUGFIX] Prevent claiming rewards when button is disabled

src/app/components/PairSelector.tsx
Resolves [393](https://github.com/DeXter-on-Radix/website/issues/393)
=> fix suggestions overflow on mobile screens

src/app/components/NavBar.tsx
Related to closed issue https://github.com/DeXter-on-Radix/website/pull/391
=> add sticky navbar on mobile views

src/app/components/PairSelector.tsx
Resolves [268](https://github.com/DeXter-on-Radix/website/issues/268)
=> [Fix]: Wrong pair selector values

src/app/components/PairSelector.tsx
resolves https://github.com/DeXter-on-Radix/website/issues/414
=> [Fix]: Pair selector shows autocomplete suggestions

src/app/components/PairSelector.tsx
fixes [428](https://github.com/DeXter-on-Radix/website/issues/428)
Please do not merge yet
=> [Fix] Pair selector minor bug

src/app/components/DisplayTable.tsx
resolves #436.
Based on this discussion:
https://t.me/dexter_discussion/16474
=> Add time completed to orderHistory

src/app/components/DisplayTable.tsx
resolves #259.
Adds sorting by time completed.
=> add sorting by time completed for order history

src/app/components/Footer.tsx
=> [BUGFIX] Fix mobile cutoff on brave mobile

src/app/components/PairSelector.tsx
=> [BUGFIX] Fix pairSelector sorting

src/app/state/orderInputSlice.ts
Fixes #425
Proposed solution is to extract the alphadex-client method and move it into the orderslice
=> customized order transaction submission

src/app/rewards/page.tsx
=> fix rewards page bug

src/app/components/NavBar.tsx, src/app/state/accountHistorySlice.ts, src/app/state/pairSelectorSlice.ts
Resolves https://github.com/DeXter-on-Radix/website/issues/445
=> [Fix]: Remove trade history on log out

CONTRIBUTING.md, src/app/components/NavBar.tsx, src/app/page.tsx
We had another instance of hydration error on the landing page caused by the language detection:
- fixes hydration errors on landing page by adding hydration fix to all landing page components
- adds improved documentation on how to handle hydration errors. I newly recommend only fixing those on demand, as its not easy to anticipate when they occur. With this new guide the action plan is pretty straightforward!
=> Fix hydration error landing page

package-lock.json, package.json, src/app/components/AccountHistory.tsx, src/app/styles/globals.css, src/app/styles/table.css, tailwind.config.js
This PR updates DaisyUI from version 3 to version 4. The update includes new components like skeleton
Implementation Details:
- Followed the official DaisyUI upgrade guide outlined in the blog post [“How to Update DaisyUI to v4”](https://daisyui.com/blog/how-to-update-daisyui-4/) to ensure proper integration and compatibility.
- Adjustments were made according to the instructions provided in the guide, including updating class names, and handling deprecated features
Added tailwind-merge to handle merging of Tailwind CSS classes, ensuring correct application of styles and avoiding conflicts.
=>  Update DaisyUI to v4 and Add tailwind-merge

.gitignore, package.json, scripts/fetchUsers.js
Some additions to the fetchUsers script:
- fixed typo
- simplified functions and error handling
- made the script runnable via `npm run fetchUsers`
- the output of each run is now also stored locally inside a file (excluded from github)
- added a row inside the google sheet to track total number of unique users and total numbers of order placed
=> Script improvements

src/app/components/Skeleton.tsx, src/app/kpis/page.tsx
- add reusable daisy-ui (v4) loading skeleton components 
- add loading skeletons to /kpis page
=> add daisy-ui loading skeleton components to /kpis

src/app/components/NavBar.tsx
add animation on the hamburger menu & animation when mobile menu open/close
=> animate hamburger button and mobile menu on open/close

CONTRIBUTING.md
This PR updates the documentation to recommend Redux DevTools for development setup. I also recorded and linked a 1 min tutorial video, as I remember having trouble onboarding and using it.
Video is here:
https://www.youtube.com/watch?v=5qrIbU1XspA
=> Add redux dev tools guide to CONTRIBUTING.md

src/app/components/PriceChart.tsx, src/app/trade/page.tsx
=> fix spacing

src/app/components/NavBar.tsx
**Fixed Issues** 
1. The menu items are not capitalized
2. When switching to portugiese, the text doesnt change.
=> Fixed Mobile NavBar text and Translation .

package-lock.json, package.json
=> update adex to 0.12.15

src/app/tester-setup/page.tsx
Added a shortlink to the tester setup guide for beta testers. For easy sharing!
=> add tester setup link forwarding

src/app/components/PairSelector.tsx
resolves #592
I could replicate and fix locally for me, can you verify it works for you too @fliebenberg ?
=> fix selection not reset when switching pairs

src/app/components/Footer.tsx, src/app/state/locales/en/footer.json, src/app/state/locales/pt/footer.json
Added a link to crumbsup page with all DAO votes in the footer for convenience / exploration.
=> add link to crumbsup in footer

src/app/components/NavBar.tsx
- add capability to open navbar items in a new tab
- open roadmap in a new tab
- fix responsiveness issues, where the items of the navbar would be overflowing. The breakpoint to have a mobile hamburger menu is now set at 840px.
=> Improve NavBar

package-lock.json, package.json
=> update alphadex sdk to latest

src/app/contribute/page.tsx
Added a route for quick sharing of github issues
=> add contribute short route
