src/app/layout.tsx

Fix #24 
I have managed to fix the documentNotDefined error by initialising the RadixDappToolkit in a useEffect() hook in the layout.tsx file.
Although this works, I think the best would be to simplify our layout.tsx and have separate compoenents for the navbar and footer. The RadixDappToolkit can then be initialised in the navbar component (that is where the button appears) still in a useEffect hook.

fix documentNotDefined error

---

src/app/components/PriceInfo.tsx
src/app/page.tsx
src/app/redux/priceInfoSlice.ts
src/app/redux/store.ts
src/app/subscriptions.ts

closes #81 
Finished price info component.
You can merge this first before merging the chart enhancement.
NOTE: I aware that styling is lacking for the volume xxx (xx.xx%).  I have some utils functions from the chart enhancement PR that I will be using for a next PRs after both can be merged.  I will also refactor both components (priceinfo and chart) that has similar function needs afterwards.

Price info bar component

---

package-lock.json
package.json

I've been using 0.10.1 on my local build and it works as expected generally. There are some intermittent issues, but I don't think that has to do with the DeXter dapp.

alphadex version bump to 0.10.1 and radix tookit bump to 1.0.0

---

src/app/components/PairSelector.tsx

pair selector and style

---

src/app/redux/priceInfoSlice.ts

Fixes #129 
The number that is coming from the alphadex api, was strange so I did the calculation on our side with the alphadex open price.
Formula: ((last-open)/open)*100
Known Issues:
Floating point precision, sometimes there are 49.99999996 in the calculation. Potential fix was parseFloat(x).toPrecision(8), but this returns a string vs a number.

Price info percent change calculation

---

src/app/components/NavBar.tsx
src/app/landing/page.tsx
src/app/markets/page.tsx
src/app/trade/page.tsx

Fixes #133 
Colors need to be tweaked a bit and some padding polish, but I can do that after the first initial reviews on nav update to align figma.
Note:
Didn't change the default page.tsx that has the current trade page as I didn't want to disturb existing PR's
Placed some filler pages for Landing, Trade, Markets
Landing: We can remove this link and put it at the root, when everyone is ready
Trade: Future location of the trade page, placeholder for now
Markets: Mock out to match Figma

Navbar update to match figma

---

src/app/components/PriceChart.tsx

Updating chart styles

---

package-lock.json
package.json
src/app/components/DisplayTable.tsx
src/app/subscriptions.ts
src/app/utils.ts

Updating the Alphadex package for stokenet
https://discord.com/channels/1125689933735145503/1125689934251032584/1168892002314752030

Alphadex package update

---

src/app/components/DisplayTable.tsx
src/app/utils.ts

Just cleaning up the placeholders and putting in the values, it seems like they were for the averaged filled price. 
I used the filled amounts for token 1 and token 2. It looked correct, but wouldn't mind a double check by someone.
Refs #179 
Fixes #157

Avg Filled and Cleaned up placeholders

---

package-lock.json
package.json

This update is required as it contained a breaking change when connecting to the AlphaDEX backend. No further updates to dexter is required.

sdk version updated to latest

---

__tests__/utils.test.ts
src/app/components/OrderBook.tsx
src/app/components/PriceChart.tsx
src/app/components/PriceInfo.tsx
src/app/components/order_input/AmountInput.tsx
src/app/redux/orderInputSlice.ts
src/app/utils.ts

fixes #191 
- Removes disparities between separator logic for different components.
- Removes the separators params from displayAmount function - we don't want users to ever pass something non-standard here (something that is different than the rest of the page). They are not needed for tests, because just mock setup ensures consistent separators.
- Ensures there is always a thousand separator (because it simplifies code and on macs for some reason even when selecting a number format with spaces - the browser thinks there is no thousands separator, "").

fixes separators logic disparities

---

src/app/redux/orderInputSlice.ts

Fixes #193 
Added some rest conditions when switching pairs to clear the states in the validationToken1 and validationToken2 as the states were carried when switching pairs.

Reset state on pair switch

---

src/app/components/OrderBook.tsx
src/app/state/orderInputSlice.ts

fixes #187
This pull request fixes the error message for amount validation in the orderbook and ensures that decimals are displayed correctly.

Fix price error message and display decimals in orderbook

---

.env.example
.gitignore
next.config.js
src/app/subscriptions.ts

prototype env vars

---

src/app/components/OrderBook.tsx

This is workaround to get correct decimals to display, as the toLocaleString solution causes issues with number display
For example: 
The problem is how Number and toLocaleString() loses precision. Example in dev console

toString instead of toLocaleString

---

src/app/components/PairSelector.tsx
src/app/components/PriceChart.tsx

fixes #219
fixes #154
- fixes strange bottom margin
- adds shortcuts for search - `/`, enter, esc, arrows
- fixes the (i) info label showing up on top of the options
- adds scrollbar (not visible unless we have more pairs)

Pair selector imporvements

---

.github/CODEOWNERS
.prettierignore

refs #23 
The CODEOWNERS file allows to set the following rule for approving PRs:
- PRs can be merged only after at least 1 code owner viewed the specified files ([developers team](https://github.com/orgs/DeXter-on-Radix/teams/developers for all files, [testers team](https://github.com/orgs/DeXter-on-Radix/teams/testers) for end to end tests 
- other people (repo/org owners, but not developers, e.g. `@Radstakes` ) will still be able to review and approve PRs and count as the second person 
- not specified in this file, but in github settings - we need at least 2 reviews per PR to be able to merge to `main`

add CODEOWNERS file

---

src/app/components/AccountHistory.tsx

Fixes #261 .
On small screens (e.g. mobile) the tabs section was causing an overflow bug. I suggest to wrap the text vertically with a narrow line height such that the tabs remain visible without the need to scroll.

remove nowrap and stack text vertically if not enough space

---

src/app/components/order_input/OrderInput.tsx
src/app/page.tsx

This PR fixes the issue mentioned by @Kafkafrate, where the grey area should take up the full width of the panel:
After:

Fix: Expand flex child to full height in trading panel

---

src/app/components/PriceChart.tsx

Fixes #269.
Just a proposal, I think it looks better when the candles are zoomed and real estate of the chart is fully used.

fix empty chart canvas

---

src/app/components/NavBar.tsx

I suggest temporarily removing the TRADE navbar element until we launch the landing page.

temporarily remove navbar element

---

src/app/components/PriceInfo.tsx

Added 2 small changes to improve the layout of the price info component:
1. centered vertically
2. Mobile: align vertical spacing to match coin selector component

Fix minor spacing issues for price info

---

CONTRIBUTING.md

I got the information how to connect to mainnet or testnet from this comment:
https://github.com/DeXter-on-Radix/website/pull/255#issuecomment-1942186043
We should put it in the official documentation for reference.
Additionally I just got my local env to work and wanted to share the setup procedure for future contributors.

Add env setup guide to contributors.md

---

src/app/components/DisplayTable.tsx

Looking at @Kafkafrate screenshot (bugreport from telegram: https://t.me/dexter_discussion/12674):
First of all, if the order was filled 100% then "Filled qty" and "Order qty" should have the same quantity and token.
Given the price is 2 XRD, this means that 5XRD were paid to buy 2.5 DEXTR. This leads me to believe, that "Filed Qty" is refering to amount in DEXTR, while "Order Qty" is referring to amount in XRD. 
To ensure both coins are always the same, this PR calculates the "Filled Qty" from scratch, which should solve this inconsistency.
(side note: I have a suspicion that [`amountFilled`](https://socket.dev/npm/package/alphadex-sdk-js/files/0.12.9/lib/models/order-receipt.d.ts#L35) is not always specified in the same token as …

Fix trade history bug

---

package-lock.json
package.json

fixes #247 
refs #197 
Updated the alphadex sdk to the latest version. The new version fixes a bug where order details were not correctly updating sometimes (#247) and also allows for seamless switching between Alphadex API endpoints to avoid downtime when alphadex does api maintenance. Therefore this PR also partially addresses #197 as the SDK will now use either of the public Alphadex APIs.

update alphadex sdk to latest version

---

src/app/components/NavBar.tsx

There was a bug where languages in the language selector (on small screens like mobiles) were perviously stacked instead of next to each other.
This PR fixes this.

fix unwanted element wrapping

---

CONTRIBUTING.md

I've seen multiple PRs introducing custom css classes. Doing so will over time result in a situation where we don't get any benefits of using TailwindCSS.

custom css warning in contributing guidelines

---

src/app/components/DisplayTable.tsx
src/app/components/order_input/OrderInput.tsx
src/app/layout.tsx
src/app/state/locales/en/trade.json
src/app/state/locales/pt/trade.json
src/app/utils.ts

Implemented toast notifications for the following user actions:
- submit order (market or limit)
- cancel order
The toast is waiting in a loading state, until the user either accepts or rejects the transaction in the wallet app.

Add toaster notifications (for submit order + cancel order)

---

.github/workflows/stokenet-deploy-main.yml
next.config.js

Tried out in [my fork](https://evgeniiavak.github.io/dexter-website/) (should have done it with the last 2 PRs as well ☺️ ) - now it should work 💯%
Previous GitHub deployment fix worked but the result was still broken, only html was accessible, styles and scripts - not:

fix routing on github pages

---

src/app/components/NavBar.tsx

This PR removes the following warning from the console. 
I tested with lighthouse but our loading state is so long (1900ms), that this improvement is very marginal and not noticable. We can debate whether it makes sense to merge or not.

preload logo

---

src/app/components/PairSelector.tsx

Nothing major, but having unique keys specified for each elements in a loop improves performance. 
I'm surprised that next lets us export the app with this error, I believe it would be better to block deployment in such a case, WDYT @EvgeniiaVak?

fix pair component missing unique key bug

---

src/app/state/radixSlice.ts

This PR adds the users login status (logged in vs not logged in) to the radix slice, which is a useful feature currently needed for the rewards page.
Its a very simple change so I am a wondering why it was postponed and marked as TODO in the first place @EvgeniiaVak , am I missing some issues here?

handle isConnected state

---

src/app/layout.tsx

When there is a page with less content than 100vh, the footer currently is glitching. This PR pushes the footer down such that it is at the bottom, even if there is no content. 
- go to https://dexteronradix.com
- open devtools and run the following command inside the console:
```js
document.querySelector(".flex-grow.grid.grid-cols-12.custom-auto-row-grids.max-w-none.divide-y-4.divide-base-300").remove()
``` 
- this should give you the "BEFORE" result (left image)
- then run the same command inside the deploy-preview, which should give you the "AFTER" result (right image)

push footer down if there is no content

---

src/app/components/NavBar.tsx

This should fix #342 . 
More context: 
having `partitioned: true` makes the cookie have a separated partition storage, meaning tracking of cookies througout multiple sites is not possible anymore (CHIPS -> cookie having independant partitioned state). 
More information here:
https://developers.google.com/privacy-sandbox/3pcd/chips
https://youtu.be/zYp0DFFmGxk?si=5R8jzweBgrGP2Tsy
It's one way that google chrome suggests to solve the tracking cookie problem.

prevent 3rd party tracking by cookie

---

src/app/layout.tsx
src/app/page.tsx
src/app/rewards/page.tsx

Move the store initialization one layer up to `Layout.tsx` to prevent duplicate store initializations.
Fixes requested change from @EvgeniiaVak : [LINK](https://github.com/DeXter-on-Radix/website/pull/312/files#r1559880353)

move store one layer up to layout

---

src/app/components/DisplayTable.tsx
src/app/state/accountHistorySlice.ts
src/app/state/locales/en/enums.json
src/app/state/locales/pt/enums.json

We currently have 2 problems:
1. TradeHistory provides no additional information compared to OrderHistory
2. OrderHistory also contains Open Orders, which is unexpected and confusing
**My suggestion** 
- remove tradeHistory for now
- Open Order should only show orders that are pending
- Order History shouly only show orders that are either cancelled or fulfilled. Pending orders are not history.
- restructured to only contain "OpenOrders" and "OrderHistory"
- removed "action" from OrderHistory, as order history now represents final state
(Additional changes / enhancements)
- replaced "COMPLETED" with "FILLED" as its more clear to the user
- de-emphasized cancelled rows by adding opacity, inspired by binance
NOTE: we should still implement "Trade Hisotry", but in a correct way, see #367 for …

[ENHANCEMENT] Improve trade history

---

CONTRIBUTING.md
src/app/state/rewardUtils.tsx

Quick fix for bug when trying to fetch 100 or more orders. Have just reduced the maximum per fetch to 90, which should fix the issue.

fixed get orders more than 100 bug

---

src/app/components/OrderInput.tsx
src/app/state/orderInputSlice.ts

This PR:
- fixes #383 
- replaces rounding with truncating on all balances shown in the frontend, to prevent situations like these:

Fix precision issue

---

.github/workflows/stokenet-deploy-main.yml

Since we currently can't merge PRs from forked repositories (due to lack of deploy preview on those), this PR tries to add the possibility to trigger deploy preview creation by setting a label "deploy-preview".
I also already created the label:
Disclaimer: This was suggested by chatGPT, I am not sure this will actually work.

Trigger deploy preview by setting label

---

src/app/rewards/page.tsx

In preparation of mobile launch I improved rewards page on mobile:
- added margin to make the card visible
- added rounded corner to make it more clear that its a card, not a section

[UI enhancment] add margin on mobile + make container rounded

---

src/app/components/DisplayTable.tsx

resolves #363 by adding an extra column `ID` to the trade history tables.
preview:

Add link to order receipt nft

---

src/app/state/pairSelectorSlice.ts

- The `pairSelector` waits for data to be fetched from Adex before updating the displayed pair.
- This results in a brief period where the `pairSelector` shows the old pair, causing a perceived lag or buggy experience for the user.
- The `pairSelector` now instantly updates to show the selected pair.
- Since the `pairSelector` already has the necessary data, it no longer waits for the data fetch to complete before displaying the new pair.
This improvement enhances user experience by eliminating the lag between selecting and displaying the new pair.

[BUGFIX] Fix lag in pair selector

---

src/app/rewards/page.tsx

Loading rewards consists of the following async actions:
-> fetchAddresses
-> fetchAccountRewards
-> fetchReciepts
-> fetchOrderRewards
Currently we don't stop execution if one of the actions fails, which leads to 3 error messages being thrown at the user at the same time (which is overwhelming). We can reduce those by adding some logic:
- if there is an error fetching addresses of the rewards component, there is no need to continue as all coninuing actions will fail
- if the NFT receipts are not properly loaded, theres no need to fetch AccountRewards, as those rely on the NFT receipts.

Reduce rewards page error toasts

---

src/app/components/PairSelector.tsx
src/app/data/BLACKLISTED_PAIRS.ts

As [discussed via Telegram](https://t.me/dexter_discussion/16662), removing deprecated WOWO/XRD pair from the frontend (as the token was migrated from WonderWoman to WOWO.

remove deprecated WOWO/XRD pair

---

CONTRIBUTING.md
package.json

Usually before submitting a PR, I run the following commands locally:
- `npm run lint` to ensure formatting is correct
- `npm run test` to run vitest unit tests
- `npm run test-integration` to run playwright integration tests
To simplify the flow I added a script that runs all commands in succession for better dev experience:
`npm run test-all`

Add `npm run test-all` script

---

src/app/rewards/page.tsx

Minor pr that resolves https://github.com/DeXter-on-Radix/website/issues/452

[Fix]: rewards chest misplaced in mobile screens

---

src/app/components/AccountHistory.tsx
src/app/utils.ts

Currently the `orderSubmitted` and `orderCompleted` timestamps from the [adex API](https://socket.dev/npm/package/alphadex-sdk-js) only return values that have minute precision. This will change in the future, but for now disabling the seconds to remove the unneccessary used space. 
We can add it back in once radix/adex fixes this issue. Here is some more context (message from [Telegram](https://t.me/alphadex_xrd/1098):

remove seconds from timestamp

---

src/app/state/pairSelectorSlice.ts

When using redux-toolkit and `createSlice()` function, modifying state is allowed, hence we can simplify the function. 
See full discussion here: #458

refactor resetBalances() reducer

---

src/app/components/AccountHistory.tsx
src/app/state/accountHistorySlice.ts

Currently you can only cancel orders from the first account selected. When selecting another account from the wallet dropdown list both cancel and batchCancel transactions fail.
This PR fixes this issue.

fix cancelling rewards not possible

---

src/app/components/StatsWidget.tsx
src/app/kpis/kpis-utils.ts

Currently the landing page shows the following "users that trust us" number inside the stats widget:
But this number is inaccurate, as it just counts all followers from instagram, youtube and telegram. 
This PR updates the numbers to actually reflect unique radix wallet addresses that used DeXter at least once since inception by using the script generated by @SiegfriedBz. 
So as an update, we have:
- 689 Users (unique wallet addresses)
- 7110 Total Orders places
Disclaimer: these numbers do not exclude trades outside of DeXter but simply count all orders on alphadex (without filtering for platformId).

add totalUsers to landing page stats widget

---

src/app/components/StatsWidget.tsx

center AnimatedCounter label in StatsWidget to fix the following issue:

fix AnimatedCounter label css

---

src/app/rewards/page.tsx
src/app/state/locales/en/rewards.json
src/app/state/locales/pt/rewards.json
src/app/state/rewardSlice.ts

Currently, when switching between accounts with no rewards, there's no indication if the fetching worked, as the UI just does not change at all. 
This PR adds a "Loading..." text whenever the app is loading rewards. That way the user gets a visual feedback whenever new rewards are loaded. This is particularly usefull if you have multiple accounts you cycle through to check for rewards, as it makes the journey more clear for the user.
The loading state looks like this:

Add loading state to rewards page

---

src/app/components/PairSelector.tsx

Enable the PairSelector menu to close when clicking outside the menu

---

src/app/components/StatsWidget.tsx
src/app/page.tsx

This PR makes the stats widget a standalone section, to make the scroll experience more natural. Previously the stats box appeared to belong to the hero section, and thus the big gap felt weird. 
Now as standalone section it feels more natural and is visually separated.
Discussion reference on discord:
https://discord.com/channels/1125689933735145503/1266737549548851252/1268980904068644936

make stats widget a standalone section

---

src/app/state/accountHistorySlice.ts

We have a bug where account history orders (for all other pairs) are only fetched for the first account. When switching accounts from the dropdown, it continues to fetch orders from the first account instead of the selected one.
Please merge ASAP. 😊

fix account history fetching bug

---

src/app/components/PriceChart.tsx

As per request form telegram, adding a link icon redirecting to the radix dashboard inside the PairInfo, for user convenience. 
Preview:

Add link to radix-dashboard to PairInfo

---

src/app/components/PriceChart.tsx

Currently there is a gap between the PairInfo and the orderInput on tablet devices, like this:
This PR fixes this gap by removing maring left and margin bottom and padding bottom. Additionaly it reduces margin of the divider on mobile to make the elements more grouped as a unit.

PairInfo small fix

---

src/app/components/Footer.tsx
src/app/state/locales/en/footer.json
src/app/state/locales/pt/footer.json

This PR adds a link in the footer linking to an MVP version of a roadmap (or more accurate feature list). 
The roadmap was created in Notion by me. I am happy to add/change things. Current version:
https://ductus.notion.site/DeXter-Roadmap-e8faed71fe1c4cdf95fb247f682c0d3a
Related to #562.

add link to roadmap in footer

---

src/app/components/PairSelector.tsx
src/app/utils.test.ts
src/app/utils.ts

Intuitive pair search

---

src/app/components/Footer.tsx
src/app/state/locales/en/footer.json
src/app/state/locales/pt/footer.json
src/app/treasury/page.tsx

This PR adds the possibility to directly get to the treasury account by going to 
dexteronradix.com/treasury
The idea being that it can be user as a shortlink to share anywhere and looks more legit than simply the radix dashboard link.
I also added the link to the footer, but did not add it to the navbar, as its a secondary action (I would even argue its a hidden action as we only really need the shortlink).

Add treasury shortlink

---

src/app/components/OrderInput.tsx
src/app/state/locales/en/errors.json
src/app/state/locales/pt/errors.json
src/app/state/orderInputSlice.ts

Added 5 commits:
1. fixed linter error: explenation: the sliderCallback always used the isMarketOrder or isLimitOrder from OUTSIDE of its function definition. This means, that every time the order type changed, the sliderCallback function definition was redefined and recomputed. This means that we don't actually need the second input (type), as it was never used. To prevent the sliderCallback from re-computing every time the order type changes, I added useCallback, which caches each sliderCallback definition and reduces recomputation costs.
2. Fixed the error where the slider set to 0 would lead to "AMOUNT MUST BE > 0" error. This was actually expected and wanted behavior, in the context of the slider it was unpractical, so I removed this validation and instead simply made the button …

buy sell panel slider improvements

---

src/app/rewards/page.tsx
src/app/utils.ts

Fixed the missing DeXter logo on the rewards page. 
The IPFS node seems to be down, so decided to hardcode the icon url only for DeXter.
Reported here:
https://t.me/dexter_discussion/21047

fix logo for details page as well

---

src/app/components/OrderBook.tsx

when trade.token1Amount being zero, division by zero occurs on Recent Orders view. This change check whether it's zero, it's return 0.

Fix division by zero error - Issue_587

---

CONTRIBUTING.md
src/app/components/DexterButton.tsx
src/app/components/NavBar.tsx
src/app/components/OrderInput.tsx
src/app/hooks.ts
src/app/layout.tsx
src/app/page.tsx
src/app/rewards/page.tsx
src/app/state/radixSlice.ts
src/app/utils.ts

This PR includes several important refactors and fixes related to client-side rendering and hydration handling. If reviewing is difficult, I'm happy to split it into smaller PRs or explain via a quick call.
- **Refactored utility functions to hooks**: Functions that relied on the `navigator` object are now client-side hooks for better safety and cleaner code. 
- `detectBrowserLanguage` → `useBrowserLanguage()`
- `isMobile` → `useMobile()`
- `detectOperatingSystem` → `useOperatingSystem()`
- **Improved hydration handling**: 
- Previous approach: Rendered an empty component until hydration was complete, then populated content.
- New approach: The default page (in English) is rendered with all UI elements during initial pageload. Once hydration completes, the saved language from cookies is …

Improve pageload

---

src/app/state/orderInputSlice.test.ts

The slider introduces a new UX, which makes the validation of zero token amounts tedious, because its not uncommon to set the slider back to 0. 
Since we don't want to trigger the error every time the user uses the slider, I think its fine to remove those tests, as the validation was removed as well.

Fix buy sell panel slider tests

---

src/app/team/page.tsx

Currently, when the user explores the contributors list by clicking the filters, the layout shifts, as the content is always being centered, and depending on filter, the content is vigger / smaller. 
This PR makes the layout always start from top, which remoevs the layout shifts, as the filter UI will always show up in the same place. 
https://github.com/user-attachments/assets/a0c77629-af56-4a4c-91dc-599d76466182
https://github.com/user-attachments/assets/b9e15c7b-74d5-4578-91ad-0d247b5c8f17

fix team page layout shifts

---

src/app/page.tsx
src/app/state/locales/en/landing.json
src/app/state/locales/pt/landing.json

Updated the text on the landing page concerning tokenomics to include the latest DAO vote to cap supply at 14.5M tokens:
**english**
**portuguese**

update tokenomics on landing page

---

src/app/components/OrderInput.tsx
src/app/state/orderInputSlice.ts

reported by [@RenatoBro on telegram](https://t.me/dexter_discussion/21992):
- whenever the token is changed via pairSelector, the app stops working properly (silently crashes without notifying user).
- users no longer can place orders or see the chart data
This bug was introduced with the Slider UI. Some explenations:
- the getQuote API from alphadex API seems to throw an error when the amount is 0, but only for mainnet (not on stokenet). Just out of curiosity: Is this true/possible @fliebenberg?
- we removed the validation tests for ZERO AMOUNT in the PR, because the slider would trigger that ERROR too often, making the UX bad. Based on that new UX with the slider, we decided to no longer throw an error if the amount is zero. Unfortunately I did not update the getQuote call.
- once I …

BUG REPORT + FIX: Selecting pairs other than DEXTR/XRD silently crashed app

---

package-lock.json
package.json
src/app/components/OrderInput.tsx

Fixes one issue of #610 , where the slider did cause the UI to randomly change values, becuase there were a ton of requests to getQuote lined up (on every change of the slider, so for 1 slide you would get like 20-50 requests). This is also leading to extensive data usage and slows down UX. 
This fix solves that issue by adding a debounce of 350ms to all slider actions, meaning the slider will call getQuote only after it hasnt been touched for 350ms.

Debounce slider

---

src/app/rakoon-revenue/page.tsx

dexteronradix.com/rakoon-revenue will now redirect to the public google sheet tracking all revenue share transactions from rakoon fun.
This is the public google sheet:
https://docs.google.com/spreadsheets/d/1xyEob71d5c2eHuQjq1P60DXaAeeuboB2nSQFztiWviU/edit?gid=0#gid=0

add rakoon-revenue shortlink
